rails/config/routes.rb
Rails.application.routes.draw do
  resources :messages
  get 'profile' => 'welcome#profile'

  root 'welcome#index'

  namespace :api do
    resources :messages, only: [:index, :show, :update]
    resources :users, only: [:show]
  end
end

rails/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  scope :unread, -> { where(read: false) }
end

rails/app/models/user.rb
class User < ActiveRecord::Base
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :messages, class_name: 'Message', foreign_key: 'recipient_id'

  def name
    "#{first_name} #{last_name}"
  end
end

rails/app/controllers/api/base_controller.rb
module Api
  class BaseController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :null_session

    def _render_with_renderer_json(json, options)
      serializer = build_json_serializer(json, options)

      if serializer
        super(serializer, options)
      else
        super(json, options)
      end
    end
  end
end

rails/app/controllers/api/messages_controller.rb
module Api
  class MessagesController < BaseController

    # obviously, this is not secure enough for real life
    def index
      messages = Message.where(recipient_id: params[:user_id])
      render json: messages
    end

    def show
      message = Message.find params[:id]
      render json: message
    end

    def update
      message = Message.find params[:id]
      message.read = params[:message][:read]
      message.save

      render json: message
    end
  end

end

rails/app/controllers/api/users_controller.rb
module Api
  class UsersController < BaseController
    def show
      @user = User.find params[:id]
      render json: @user
    end
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find params[:id]
    @message.update_attributes(read: true)
  end
end

rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def profile
    @user = User.find 1
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messages</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header" class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
          <i class="icon-reorder"></i>
      </button>
      <a class="navbar-brand" href="/">
        My Cool Message App
      </a>
    </div>
    <nav class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to messages_path do %>
            Inbox <span id="unread-count" class="badge"><%= Message.unread.count %></span>
          <% end %>
        </li>
        <li>
          <%= link_to 'Profile', profile_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i><%= User.first.name %><i class="icon-sort-down"></i></a>
            <ul class="dropdown-menu pull-right">
                <li><a href="#">Log Out</a></li>
            </ul>
        </li>
      </ul>
    </nav>
  </div>
  <div id="wrapper">
    <%= yield %>
  </div>
</body>
</html>

rails/app/views/messages/_full_message.html.erb
<div class="full-message">
  <div class="header">
    <div class="row">
      <div class="col-md-12">
        <div class="pull-right"><%= @message.created_at %></div>
        <div class="subject"><%= @message.subject %></div>
      </div>
    </div>
    <div><%= image_tag @message.sender.image, class: 'sender-image' %><%= render @message.sender %> <span class="to">to</span> <%= image_tag @message.recipient.image, class: 'sender-image' %><%= render @message.recipient %></div>
  </div>

  <hr>

  <div class="body">
    <%= @message.body %>
  </div>
</div>

rails/app/views/messages/_message.html.erb
<li>
  <% is_read_css = message.read ? 'read' : '' %>
  <%= link_to message_url(message), remote: true, class: "read-message-link #{is_read_css}" do %>
    <div class="pull-right"><%= message.created_at %></div>
    <div class="from"><%= render message.sender %></div>
    <div class="subject"><%= message.subject %></div>
    <div class="body"><%= message.body[0, 100] %></div>
  <% end %>
</li>

rails/app/views/messages/index.html.erb
  <div id="sidebar-wrapper" class="col-md-3">
    <div id="sidebar">
      <ul id="message-list" class="nav list-group">
        <%= render @messages %>
      </ul>
    </div>
  </div>
  <div id="main-wrapper" class="col-md-9 pull-right">
    <div id="main">
      <div class="page-header">
        <h3>Messages</h3>
        <p>Click on a message on the left to view it.</p>
      </div>
    </div>
  </div>

rails/app/views/messages/show.js.erb
$('#main').html('<%= j render 'full_message' %>');

<% unread_count = Message.unread.count %>
$('#unread-count').text(<%= unread_count %>);

rails/app/views/users/_user.html.erb
<strong><%= user.name %></strong> &lt;<%= user.email %>&gt;

rails/app/views/welcome/index.html.erb
<div id="main-wrapper-index" class="col-md-12">
  <h2>Welcome to the best message app evar.</h2>
</div>

rails/app/views/welcome/profile.html.erb
<div class="profile">
  <h2>My Profile</h2>

  <div class="image"><%= image_tag @user.image %></div>
  <div class="name">
    <%= @user.name %>
  </div>
  <div class="email">
    <%= @user.email %>
  </div>
</div>